USE [MikroDB_V15_DGP1399]
GO

/****** Object:  Table [dbo].[TERP_COST]    Script Date: 24.04.2021 18:06:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TERP_COST](
	[GUID] [uniqueidentifier] NOT NULL,
	[MONTH] [smallint] NULL,
	[YEAR] [smallint] NULL,
	[CODE] [nvarchar](50) NULL,
	[COST] [float] NULL,
	[LAST_QUANTITY] [float] NULL,
 CONSTRAINT [PK_TERP_COST] PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TERP_COST] ADD  CONSTRAINT [DF_TERP_COST_GUID]  DEFAULT (newid()) FOR [GUID]
GO


