USE [MikroDB_V15_DGP1399]
GO

/****** Object:  Table [dbo].[TERP_SEMSI_PERIOD]    Script Date: 24.04.2021 18:06:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TERP_SEMSI_PERIOD](
	[GUID] [uniqueidentifier] NOT NULL,
	[YEAR] [smallint] NULL,
	[MONTH] [smallint] NULL,
	[NAME] [nvarchar](25) NULL,
	[MILADI] [nvarchar](50) NULL,
	[START_DATE] [datetime] NULL,
	[END_DATE] [datetime] NULL,
 CONSTRAINT [PK_TERP_SEMSI_PERIOD] PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TERP_SEMSI_PERIOD] ADD  CONSTRAINT [DF_TERP_SEMSI_PERIOD_GUID]  DEFAULT (newid()) FOR [GUID]
GO


